In [1]:
import pandas as pd

In [6]:
x = pd.DataFrame(['a', 'b', 'a', 'c'], columns= ['clase'])
x

clase
0     a
1     b
2     a
3     c

In [7]:
dicc = {'a': 1, 'b': 2, 'c': 3}
x['clase'].map(dicc)

0    1
1    2
2    1
3    3
Name: clase, dtype: int64

In [11]:
dicc.keys()

dict_keys(['a', 'b', 'c'])

In [12]:
import numpy as np

In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y, x.size

(array([5, 7, 9]), 3)

In [18]:
z = np.array([[5, 6, 7], [8, 1, 7], [6, 4, 3]])
z

array([[5, 6, 7],
       [8, 1, 7],
       [6, 4, 3]])

In [19]:
z[1,2]

7

In [20]:
z[1]

array([8, 1, 7])

In [21]:
z[1][2]

7

In [22]:
z[:2]

array([[5, 6, 7],
       [8, 1, 7]])

In [23]:
z[:, 2]

array([7, 7, 3])

In [24]:
z = np.array([[5, 6, 7, 9], [8, 1, 7, 0], [6, 4, 3, 1]])
z

array([[5, 6, 7, 9],
       [8, 1, 7, 0],
       [6, 4, 3, 1]])

In [29]:
#Dos ultimas filas
z[-2:]

array([[8, 1, 7, 0],
       [6, 4, 3, 1]])

In [31]:
#Primea fila con sus dos ultimas columnas
z[0][-2:]

array([7, 9])

In [33]:
#Suma de la matriz
np.sum(z)

57

In [34]:
#Suma de las columnas
np.sum(z, axis=0)

array([19, 11, 17, 10])

In [35]:
#Suma de las filas
np.sum(z, axis=1)

array([27, 16, 14])

In [39]:
np.zeros([2, 2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [41]:
np.ones([2, 2]).astype('int')

array([[1, 1],
       [1, 1]])

In [48]:
r = np.random.random(10)
r.mean(), r.std()


(0.35175947923114248, 0.32495294186489321)

In [50]:
x = [1,2,3]
np.log(x), np.exp(x), np.power(x, 2), np.sqrt(x)

(array([ 0.        ,  0.69314718,  1.09861229]),
 array([  2.71828183,   7.3890561 ,  20.08553692]),
 array([1, 4, 9]),
 array([ 1.        ,  1.41421356,  1.73205081]))