In [2]:
import nltk
# nltk.download('all')
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import random
import string

In [6]:
with open('chatbot.txt','r',errors = 'ignore') as f:
    raw=f.read().lower()
raw[:1000]

'a chatbot (also known as a talkbot, chatterbot, bot, im bot, interactive agent, or artificial conversational entity) is a computer program or an artificial intelligence which conducts a conversation via auditory or textual methods. such programs are often designed to convincingly simulate how a human would behave as a conversational partner, thereby passing the turing test. chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition. some chatterbots use sophisticated natural language processing systems, but many simpler systems scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database.\n\nthe term "chatterbot" was originally coined by michael mauldin (creator of the first verbot, julia) in 1994 to describe these conversational programs.today, most chatbots are either accessed via virtual assistants such as google assistant and amazon

In [8]:
sent_tokens = nltk.sent_tokenize(raw)
word_tokens = nltk.word_tokenize(raw)

print(sent_tokens[:5])
print("/"*50)
print(word_tokens[:15])

['a chatbot (also known as a talkbot, chatterbot, bot, im bot, interactive agent, or artificial conversational entity) is a computer program or an artificial intelligence which conducts a conversation via auditory or textual methods.', 'such programs are often designed to convincingly simulate how a human would behave as a conversational partner, thereby passing the turing test.', 'chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition.', 'some chatterbots use sophisticated natural language processing systems, but many simpler systems scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database.', 'the term "chatterbot" was originally coined by michael mauldin (creator of the first verbot, julia) in 1994 to describe these conversational programs.today, most chatbots are either accessed via virtual assistants such as google assistant 

In [9]:
lemmer = nltk.stem.WordNetLemmatizer()
print("lemmer ", lemmer, type(lemmer))

def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

print("remove_punct_dict ", remove_punct_dict, type(remove_punct_dict))

lemmer  <WordNetLemmatizer> <class 'nltk.stem.wordnet.WordNetLemmatizer'>
remove_punct_dict  {33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None} <class 'dict'>


In [10]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

sent_proof = 'a chatbot (also known as a talkbot, chatterbot, bot, im bot, interactive agent, or artificial conversational entity) is a computer program or an artificial intelligence which conducts a conversation via auditory or textual methods.'

print(LemNormalize(sent_proof))

['a', 'chatbot', 'also', 'known', 'a', 'a', 'talkbot', 'chatterbot', 'bot', 'im', 'bot', 'interactive', 'agent', 'or', 'artificial', 'conversational', 'entity', 'is', 'a', 'computer', 'program', 'or', 'an', 'artificial', 'intelligence', 'which', 'conduct', 'a', 'conversation', 'via', 'auditory', 'or', 'textual', 'method']


In [30]:
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["hi", "hey", "hi there", "hello", "I am glad! You are talking to me"]

def greeting(sentence):
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)
    return '-'

print(greeting('hi mon'))
print(greeting('goog morning'))
print(greeting('sup now'))
print(greeting('hello go'))
print(greeting('bad day'))

hi there
-
hello
hey
-


In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
list_tokens = sent_tokens[:5]
list_tokens

['a chatbot (also known as a talkbot, chatterbot, bot, im bot, interactive agent, or artificial conversational entity) is a computer program or an artificial intelligence which conducts a conversation via auditory or textual methods.',
 'such programs are often designed to convincingly simulate how a human would behave as a conversational partner, thereby passing the turing test.',
 'chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition.',
 'some chatterbots use sophisticated natural language processing systems, but many simpler systems scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database.',
 'the term "chatterbot" was originally coined by michael mauldin (creator of the first verbot, julia) in 1994 to describe these conversational programs.today, most chatbots are either accessed via virtual assistants such as google assist

In [57]:
TfidfVec_kv = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
tfidf = TfidfVec_kv.fit_transform(list_tokens)
tfidf

<5x82 sparse matrix of type '<class 'numpy.float64'>'
	with 87 stored elements in Compressed Sparse Row format>

In [58]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.20519418, 0.        ,
         0.        , 0.        , 0.41038835, 0.        , 0.20519418,
         0.        , 0.41038835, 0.20519418, 0.        , 0.16554937,
         0.        , 0.        , 0.20519418, 0.20519418, 0.20519418,
         0.13742093, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.20519418, 0.        , 0.        ,
         0.        , 0.20519418, 0.        , 0.        , 0.        ,
         0.        , 0.20519418, 0.20519418, 0.        , 0.        ,
         0.20519418, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.20519418, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.16554937, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.20519418, 0.        , 0.        ,
         0.20519418, 0.        , 0

In [59]:
print(TfidfVec_kv.get_feature_names())

['1994', 'accessed', 'acquisition', 'agent', 'alexa', 'amazon', 'apps', 'artificial', 'assistant', 'auditory', 'behave', 'bot', 'chatbot', 'chatbots', 'chatterbot', 'chatterbots', 'coined', 'computer', 'conduct', 'conversation', 'conversational', 'convincingly', 'creator', 'customer', 'database', 'designed', 'dialog', 'entity', 'facebook', 'google', 'human', 'im', 'including', 'individual', 'information', 'input', 'intelligence', 'interactive', 'julia', 'keywords', 'known', 'language', 'matching', 'mauldin', 'messaging', 'messenger', 'method', 'michael', 'natural', 'organization', 'originally', 'partner', 'passing', 'pattern', 'practical', 'processing', 'program', 'programstoday', 'pull', 'purpose', 'reply', 'scan', 'service', 'similar', 'simpler', 'simulate', 'sophisticated', 'talkbot', 'term', 'test', 'textual', 'turing', 'typically', 'use', 'used', 'various', 'verbot', 'virtual', 'wa', 'website', 'wechat', 'wording']


In [60]:
vals = cosine_similarity(tfidf[-1], tfidf)
vals

array([[0.03942072, 0.02466149, 0.03332246, 0.        , 1.        ]])

In [61]:
vals.argsort()

array([[3, 1, 2, 0, 4]])

In [75]:
idx=vals.argsort()[0][-2]
idx

0

In [66]:
flat = vals.flatten()
flat

array([0.03942072, 0.02466149, 0.03332246, 0.        , 1.        ])

In [67]:
flat.sort()
flat

array([0.        , 0.02466149, 0.03332246, 0.03942072, 1.        ])

In [69]:
req_tfidf = flat[-2]
req_tfidf

0.03942072270417901

In [76]:
sent_tokens[idx]

'a chatbot (also known as a talkbot, chatterbot, bot, im bot, interactive agent, or artificial conversational entity) is a computer program or an artificial intelligence which conducts a conversation via auditory or textual methods.'

### PROBANDO TODO JUNTO EN FUNCION:

In [78]:
def chat_kv(sent_tokens, user_response, tokenizer):
    robo_response=''
    sent_tokens.append(user_response)
    
    TfidfVec = TfidfVectorizer(
        tokenizer=tokenizer, 
        stop_words='english'
    )
    
    tfidf = TfidfVec.fit_transform(sent_tokens)
    
    vals = cosine_similarity(tfidf[-1], tfidf)
    print("comparacion por cosenos : ", vals)
    
    idx = vals.argsort()[0][-2]
    print("indice con mas similitud : ", idx)
    
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    
    print('------> ', req_tfidf)
    if req_tfidf == 0:
        robo_response=robo_response + "------ NOLA ------"
        return robo_response
    else:
        robo_response = robo_response + sent_tokens[idx]
        return robo_response

chat_kv(sent_tokens, 'Hola amigos', LemNormalize)

comparacion por cosenos :  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
indice con mas similitud :  25
------>  0.0


'------ NOLA ------'