In [28]:
import numpy as np
initialProb = np.array([[0.25],[0.75]])
transProb = np.array([[0.7, 0.3],[0.1, 0.9]])
obsProb = np.array([[0.9, 0.1],[0.2, 0.8]])

class Viterbi(object):
    def __init__(self, initialProb, transProb, obsProb):
        self.N = initialProb.shape[0]
        self.initialProb = initialProb
        self.transProb = transProb
        self.obsProb = obsProb
        print(self.initialProb.shape)
        print(initialProb.shape[0])
        assert self.initialProb.shape == (self.N, 1)
        print("//////////////////////")
        
        assert self.transProb.shape == (self.N, self.N)
        assert self.obsProb.shape[0] == self.N
 
    def Obs(self, obs):
        return self.obsProb[:, obs, None]
 
    def run(self, obs):
        trellis = np.zeros((self.N, len(obs)))
        backpt = np.ones((self.N, len(obs)), 'int32') * -1
 
        trellis[:, 0] = np.squeeze(self.initialProb * self.Obs(obs[0]))
        print(trellis[:, 0])
         
        for t in range(1, len(obs)):
            trellis[:, t] = (trellis[:, t-1, None].dot(self.Obs(obs[t]).T) * self.transProb).max(0)
            print("trellis: ", trellis[:, t])
            backpt[:, t] = (np.tile(trellis[:, t-1, None], [1, self.N]) * self.transProb).argmax(0)
            print("backpt: ", trellis[:, t])
        
        tokens = [trellis[:, -1].argmax()]
        for i in range(len(obs)-1, 0, -1):
            tokens.append(backpt[tokens[-1], i])
        return tokens[::-1]
    
algoritmo = Viterbi(initialProb, transProb, obsProb)
mas_probable = algoritmo.run([0, 1, 1])
print("##############################")
print(mas_probable)

(2, 1)
2
//////////////////////
[ 0.225  0.15 ]
trellis:  [ 0.01575  0.108  ]
backpt:  [0 1]
trellis:  [ 0.0099225  0.01944  ]
backpt:  [0 1]
--------------------------------
[[ 0.225      0.01575    0.0099225]
 [ 0.15       0.108      0.01944  ]]
--------------------------------
[[-1  0  0]
 [-1  1  1]]
##############################
[1, 1, 1]
